### ISSUE TITLE
Configuration files should not need templating

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#70]
At the moment, a path replacement needs to be configured and created in the yaml file from a template. Such steps should only be required in testing or QMSTR development environments.

**Comment by hemarkus** [comment]
This needs clarification: you only need to configure the path substitution when running qmstr-master in a container because qmstr-wapper or gradle plugin will insert local paths into the database that do not make sense in qmstr-master container. 
The templating is used to inject this local path into the qmstr configuration so the qmstr-master server knows how to "fix" paths from the database.

We could introduce some functionality into the qmstr-master trying to guess/detect the path elements to substitute. This needs to be done in the build phase and ideally only if running containerized.

**Comment by mirkoboehm** [comment]
This one is solved, right?

**Comment by GiasemiSh** [comment]
Yes it's solved.  Pull request is here:  https://github.com/QMSTR/qmstr/pull/96
